CREATE TABLE rescue_centers{
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(100) NOT NULL,
    city VARCHAR(100) NOT NULL,

    CONSTRAINT PK_rescue_centers_id PRIMARY KEY (id),
    CONSTRAINT UQ_rescue_centers_code UNIQUE (code)

    };

CREATE TABLE rescue_cases{
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rescue_center_id BIGINT NOT NULL,
    case_code VARCHAR(100) NOT NULL,
    rescue_date DATE NOT NULL,
    rescue_location VARCHAR(100) NOT NULL,
    status VARCHAR(30) NOT NULL


    CONSTRAINT PK_rescue_centers_id PRIMARY KEY (id),
    CONSTRAINT FK_rescue_cases_rescue_center_id FOREIGN KEY (rescue_center_id),
    CONSTRAINT UQ_rescue_cases_code UNIQUE (case_code),
    CONSTRAINT CHK_rescue_cases_status CHECK (status IN ('ADMITTED', 'UNDER_EVALUATION', 'IN_REHABILITATION', 'READY_FOR_RELEASE', 'RELEASED', 'CLOSED'))

    };

CREATE TABLE animal{
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    animal_code VARCHAR(100) NOT NULL,
    common_name VARCHAR(100) NOT NULL,
    scientific_name VARCHAR(100) NOT NULL,
    sex VARCHAR(100) NOT NULL,
    rescue_case_id BIGINT

    CONSTRAINT PK_animal_id PRIMARY KEY (id),
    CONSTRAINT FK_animal_rescue_case_id FOREIGN KEY (rescue_center_id),
    CONSTRAINT UQ_animal_rescue_case_id UNIQUE (rescue_case_id),
    CONSTRAINT UQ_animal_code UNIQUE (animal_code)

    };

CREATE TABLE medical_record{
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    animal_id BIGINT NOT NULL,
    initial_weight DECIMAL NOT NULL,
    initial_condition VARCHAR(100) NOT NULL,
    injuries TEXT NOT NULL,
    observation TEXT NOT NULL,

    CONSTRAINT PK_medical_record_id PRIMARY KEY (id),
    CONSTRAINT FK_medical_record_animal_id FOREIGN KEY (animal_id),
    CONSTRAINT UQ_medical_record_animal_id UNIQUE (animal_id),

    };

CREATE TABLE specialist{
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    professional_code VARCHAR(100) NOT NULL,
    first_name VARCHAR(150) NOT NULL,
    last_name VARCHAR(150) NOT NULL,
    email VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT PK_specialits_id PRIMARY KEY (id),
    CONSTRAINT UQ_specialist_professional_code UNIQUE (professional_code),
    CONSTRAINT UQ_specialist_email UNIQUE (email)

    };

CREATE TABLE expertise {

    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(150) NOT NULL,

    CONSTRAINT PK_expertise_id PRIMARY KEY (id),
    CONSTRAINT UQ_expertise_name UNIQUE (name)

    }

CREATE specialist_expertise {
       specialist_id BIGINT NOT NULL,
       expertise_id BIGINT NOT NULL,

       CONSTRAINT PK_specialist_expertise_id PRIMARY KEY (specialist_id,expertise_id),
       CONSTRAINT FK_specialist_expertise_specialist_id FOREIGN KEY (specialist_id),
       CONSTRAINT FK_specialist_expertise_expertise_id FOREIGN KEY (expertise_id)
}

CREATE TABLE treatments{
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    animal_id BIGINT NOT NULL,
    specialist_id BIGINT NOT NULL,
    performed_at TIMESTAMP NOT NULL,
    type VARCHAR(100) NOT NULL,
    description TEXT,

    CONSTRAINT PK_treatmeants_id PRIMARY KEY (id),
    CONSTRAINT FK_treatments_specialist_id FOREIGN KEY (specialist_id),
    CONSTRAINT FK_treatments_animal_id FOREIGN KEY (animal_id),
    CONSTRAINT UQ_specialist_professional_code UNIQUE (professional_code),
    CONSTRAINT UQ_specialist_email UNIQUE (email)

    };

CREATE INDEX idx_rescue_cases_rescue_center
    ON rescue_cases(rescue_center_id);

CREATE INDEX idx_rescue_cases_status
    ON rescue_cases(status);

CREATE INDEX idx_rescue_cases_rescue_date
    ON rescue_cases(rescue_date);

CREATE INDEX idx_treatments_animal
    ON treatments(animal_id);

CREATE INDEX idx_treatments_specialist
    ON treatments(specialist_id);

CREATE INDEX idx_treatments_performed_at
    ON treatments(performed_at);